import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <Navbar />
        {children}

        <script src="https://harsh-kumar-saaniya.github.io/Chat-UI-Widget/script.js"
   data-assistant-name="Mr.Coffee"
  data-assistant-avatar="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
  data-footer-text="Powered by Aioraa"
  data-chat-button="#3B260C"
  data-chat-header="#461901"
  data-user-bubble="#33334d"
  data-bot-bubble="#3B260C"
  data-footer-bg="#461901"
  data-chat-bg="#E8DDD3"
  data-input-bg="#E8DDD3"
  data-input-color="#4C3820"
  data-send-button="#E8DDD3"
  data-send-hover="#33334d"
  data-choice-bg="#5c4dff"
  data-choice-color="#461901"
  data-choice-hover="#4a3dcf"
  data-enable-typing="true"
  data-auto-welcome="true"
        >
        
        
        </script>
      </body>
    </html>
  );
}
